/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      colors: {
        primary:   { DEFAULT: '#1A73E8', hover: '#1557B0', light: '#E8F0FE', dark: '#0D47A1' },
        surface:   { DEFAULT: '#FFFFFF', 2: '#F8F9FA', 3: '#F1F3F4' },
        border:    { DEFAULT: '#E8EAED', strong: '#DADCE0' },
        success:   { DEFAULT: '#34A853', light: '#E6F4EA' },
        warning:   { DEFAULT: '#FBBC04', light: '#FEF7E0' },
        error:     { DEFAULT: '#EA4335', light: '#FCE8E6' },
        info:      { DEFAULT: '#4285F4', light: '#E8F0FE' },
        text: {
          primary:   '#202124',
          secondary: '#5F6368',
          tertiary:  '#80868B',
          disabled:  '#BDC1C6',
          inverse:   '#FFFFFF',
          link:      '#1A73E8',
        },
        priority: {
          critical: '#EA4335',
          high:     '#FA7B17',
          medium:   '#FBBC04',
          low:      '#34A853',
        },
        status: {
          open:        '#4285F4',
          assigned:    '#9334E6',
          'in-progress': '#FA7B17',
          completed:   '#34A853',
          closed:      '#80868B',
        },
      },
      boxShadow: {
        1: '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.08)',
        2: '0 4px 6px rgba(0,0,0,0.07), 0 2px 4px rgba(0,0,0,0.06)',
        3: '0 8px 24px rgba(0,0,0,0.10), 0 4px 8px rgba(0,0,0,0.06)',
        4: '0 16px 40px rgba(0,0,0,0.12), 0 8px 16px rgba(0,0,0,0.08)',
        focus: '0 0 0 3px rgba(26,115,232,0.25)',
        'focus-error': '0 0 0 3px rgba(234,67,53,0.25)',
      },
      borderRadius: {
        sm:   '4px',
        md:   '8px',
        lg:   '12px',
        xl:   '16px',
        '2xl':'24px',
      },
      spacing: {
        '4.5': '18px',
        '13':  '52px',
        '15':  '60px',
        '18':  '72px',
        '22':  '88px',
      },
      transitionDuration: {
        150: '150ms',
        200: '200ms',
        300: '300ms',
      },
      animation: {
        'fade-in':    'fadeIn 200ms ease-out',
        'slide-up':   'slideUp 200ms ease-out',
        'scale-in':   'scaleIn 150ms ease-out',
        'slide-down': 'slideDown 200ms ease-out',
        'bounce-dot': 'bounceDot 1.4s infinite ease-in-out both',
      },
      keyframes: {
        fadeIn:    { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideUp:   { from: { opacity: '0', transform: 'translateY(16px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideDown: { from: { opacity: '0', transform: 'translateY(-8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn:   { from: { opacity: '0', transform: 'scale(0.95)' }, to: { opacity: '1', transform: 'scale(1)' } },
        bounceDot: { '0%, 80%, 100%': { transform: 'scale(0)' }, '40%': { transform: 'scale(1)' } },
      },
      width:  { sidebar: '240px', 'sidebar-sm': '64px' },
      height: { header: '64px' },
      minHeight: { 'touch': '44px' },
      minWidth:  { 'touch': '44px' },
    },
  },
  plugins: [],
}
