ALTER TABLE tasks
  ADD COLUMN IF NOT EXISTS rating INT,
  ADD COLUMN IF NOT EXISTS points INT;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS total_points INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rating_sum INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rating_count INT DEFAULT 0;
