ALTER TABLE users
  ADD COLUMN IF NOT EXISTS bio        TEXT,
  ADD COLUMN IF NOT EXISTS avatar_url TEXT,
  ADD COLUMN IF NOT EXISTS skills     TEXT[]  DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS resume_url TEXT;

CREATE INDEX IF NOT EXISTS idx_users_skills ON users USING GIN(skills);
